version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: "SEOnaut-db"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=seonaut
      - MYSQL_USER=seonaut
      - MYSQL_PASSWORD=seonaut
    networks:
      - fullstack

  app:
    build: .
    container_name: "SEOnaut-app"
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge